### Read the data from the input Excel file

In [1]:
pip install pulp

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
inputFileName = "TransportationPb_Data.xlsx"
paramDF = pd.read_excel(inputFileName, "Param", skiprows=0)
supplyDF = pd.read_excel(inputFileName, "Supply", skiprows=0, index_col=0)
demandDF = pd.read_excel(inputFileName, "Demand", skiprows=0, index_col=0)
freightDF = pd.read_excel(inputFileName, "Freight", skiprows=0, index_col=2)


### Set the data into dict, easier to manipulate

In [24]:
demandDF

Demand
Market        
M1          38
M2         129
M3         104
M4          75
M5         126
M6          90
M7         105
M8          91
M9          47
M10         61

In [3]:
plants = supplyDF.to_dict('index')
markets = demandDF.to_dict('index')
   

freightCost = {}  #freightCost[iPlant][iMarket]
for index, row in freightDF.iterrows():
    if row['Plant'] not in freightCost : freightCost[row['Plant']] = {}
    freightCost[row['Plant']][row['Market']] = row['Cost']
    

In [4]:
# fct obj : min cost st demands are verfied
from pulp import *
prob = LpProblem("Transportation_problem",LpMinimize)

### Add variables


In [5]:
Xvar = LpVariable.dicts("X", ((i,j) for i in plants for j in markets), 
                             lowBound=0, cat='Continuous')
DemandVar= LpVariable.dicts("Demand", (i for i in markets), lowBound=0, cat='Continuous')
CapacityVar= LpVariable.dicts("Capacity", (i for i in plants), lowBound=0, cat='Continuous')


### Add objectives

In [6]:
prob += lpSum([(freightCost[i][j] + plants[i]['Cost'])* Xvar[i,j] for i in plants for j in markets ])

In [7]:
#Notre problème renferme 200 variables Xij, 20 contraintes Capa, 10 contraintes de demand

In [8]:
# for i in plants.keys():
#     for j in markets.keys():
#         print(Xvar[i,j])

### Add constraints

In [9]:
#Capacity constraint (for each plant)
for i in (plants) : 
        prob += lpSum(Xvar[i,j] for j in markets) <= plants[i]['Capacity'] , "capacity[%s]"%(i)



In [10]:
# # #Demand constraint
for j in (markets) :
    prob += lpSum(Xvar[i,j] for i in plants) >= markets[j]['Demand'] , "demand[%s]"%(j)

In [11]:
prob

Transportation_problem:
MINIMIZE
19*X_('P1',_'M1') + 22*X_('P1',_'M10') + 17*X_('P1',_'M2') + 18*X_('P1',_'M3') + 19*X_('P1',_'M4') + 22*X_('P1',_'M5') + 16*X_('P1',_'M6') + 17*X_('P1',_'M7') + 15*X_('P1',_'M8') + 16*X_('P1',_'M9') + 13*X_('P10',_'M1') + 16*X_('P10',_'M10') + 14*X_('P10',_'M2') + 12*X_('P10',_'M3') + 16*X_('P10',_'M4') + 18*X_('P10',_'M5') + 17*X_('P10',_'M6') + 14*X_('P10',_'M7') + 14*X_('P10',_'M8') + 18*X_('P10',_'M9') + 14*X_('P11',_'M1') + 10*X_('P11',_'M10') + 9*X_('P11',_'M2') + 13*X_('P11',_'M3') + 13*X_('P11',_'M4') + 10*X_('P11',_'M5') + 12*X_('P11',_'M6') + 14*X_('P11',_'M7') + 12*X_('P11',_'M8') + 7*X_('P11',_'M9') + 29*X_('P12',_'M1') + 26*X_('P12',_'M10') + 30*X_('P12',_'M2') + 32*X_('P12',_'M3') + 23*X_('P12',_'M4') + 28*X_('P12',_'M5') + 28*X_('P12',_'M6') + 27*X_('P12',_'M7') + 26*X_('P12',_'M8') + 26*X_('P12',_'M9') + 34*X_('P13',_'M1') + 32*X_('P13',_'M10') + 32*X_('P13',_'M2') + 31*X_('P13',_'M3') + 35*X_('P13',_'M4') + 33*X_('P13',_'M5') + 27*X_('P

In [12]:
#prob.writeLP("blenderProblem.lp", writeSOS=1, mip=1)
prob.solve()
print("Status:", LpStatus[prob.status])
print ("Objective = ", value(prob.objective))
varsDict = {}
for v in prob.variables():
    varsDict[v.name] = v.varValue
    if "X" in v.name:
        print(v.name, "=", v.varValue)
        


Status: Optimal
Objective =  16847.0
X_('P1',_'M1') = 0.0
X_('P1',_'M10') = 0.0
X_('P1',_'M2') = 80.0
X_('P1',_'M3') = 0.0
X_('P1',_'M4') = 0.0
X_('P1',_'M5') = 0.0
X_('P1',_'M6') = 0.0
X_('P1',_'M7') = 0.0
X_('P1',_'M8') = 0.0
X_('P1',_'M9') = 0.0
X_('P10',_'M1') = 0.0
X_('P10',_'M10') = 0.0
X_('P10',_'M2') = 0.0
X_('P10',_'M3') = 2.0
X_('P10',_'M4') = 0.0
X_('P10',_'M5') = 0.0
X_('P10',_'M6') = 0.0
X_('P10',_'M7') = 0.0
X_('P10',_'M8') = 0.0
X_('P10',_'M9') = 0.0
X_('P11',_'M1') = 0.0
X_('P11',_'M10') = 0.0
X_('P11',_'M2') = 44.0
X_('P11',_'M3') = 0.0
X_('P11',_'M4') = 0.0
X_('P11',_'M5') = 0.0
X_('P11',_'M6') = 0.0
X_('P11',_'M7') = 0.0
X_('P11',_'M8') = 0.0
X_('P11',_'M9') = 12.0
X_('P12',_'M1') = 0.0
X_('P12',_'M10') = 0.0
X_('P12',_'M2') = 0.0
X_('P12',_'M3') = 0.0
X_('P12',_'M4') = 75.0
X_('P12',_'M5') = 0.0
X_('P12',_'M6') = 0.0
X_('P12',_'M7') = 0.0
X_('P12',_'M8') = 7.0
X_('P12',_'M9') = 8.0
X_('P13',_'M1') = 0.0
X_('P13',_'M10') = 0.0
X_('P13',_'M2') = 0.0
X_('P13',_'M3') = 

Problème Dual 

In [13]:
#Le nombre de variables du pb dual = nb de contraintes du primal
#Le nb de contraintes du pb dual = nb de variables du primal

In [14]:
for name, c in list(prob.constraints.items()):
     if "capacity" in name or "demand" in name:
        print(name, ":", c.pi, "\t\t", c.slack)

capacity_P1_ : -14.0 		 -0.0
capacity_P2_ : -21.0 		 -0.0
capacity_P3_ : 0.0 		 11.0
capacity_P4_ : 0.0 		 -0.0
capacity_P5_ : -10.0 		 -0.0
capacity_P6_ : -20.0 		 -0.0
capacity_P7_ : -23.0 		 -0.0
capacity_P8_ : -9.0 		 -0.0
capacity_P9_ : 0.0 		 53.0
capacity_P10_ : -18.0 		 -0.0
capacity_P11_ : -22.0 		 -0.0
capacity_P12_ : -3.0 		 -0.0
capacity_P13_ : -2.0 		 -0.0
capacity_P14_ : -7.0 		 -0.0
capacity_P15_ : 0.0 		 15.0
capacity_P16_ : -16.0 		 -0.0
capacity_P17_ : -6.0 		 -0.0
capacity_P18_ : -8.0 		 -0.0
capacity_P19_ : -7.0 		 -0.0
capacity_P20_ : -11.0 		 -0.0
demand_M1_ : 29.0 		 -0.0
demand_M2_ : 31.0 		 -0.0
demand_M3_ : 30.0 		 -0.0
demand_M4_ : 26.0 		 -0.0
demand_M5_ : 29.0 		 -0.0
demand_M6_ : 29.0 		 -0.0
demand_M7_ : 29.0 		 -0.0
demand_M8_ : 29.0 		 -0.0
demand_M9_ : 29.0 		 -0.0
demand_M10_ : 29.0 		 -0.0


2-  Why does it make sense to interpret the dual variables associated
 with the Demand constraints as prices

In [15]:
#==> Dans le problème Dual, on adopte une autre stratégie pour voir le problème
#primal : point de vue production :on veut minimiser le cout (transport+production)
#dual : point de vue Gain : on veut maximiser les marges, il s'agit donc de prix

3- Observe that for the obtained price , the obtained flows are such that each supplier is maximising its
margin






In [16]:
#Le modèle cherche à se positionner sur le cout de transport minimum pour chaque supplier
#(le min global du modèle ~ somme des min locaux de chaque supplier)

4- Impose a constraint stating that a supplier shall have not more than 50% of market share on any
market . What is the impact on the prices ?

In [17]:
# # #New constraint
for i in (plants):
  for j in (markets):
    prob += Xvar[i,j] <= 0.5 * markets[j]['Demand'],"New_constraint plant[%s] market[%s]"%(i,j)

In [18]:
prob

Transportation_problem:
MINIMIZE
19*X_('P1',_'M1') + 22*X_('P1',_'M10') + 17*X_('P1',_'M2') + 18*X_('P1',_'M3') + 19*X_('P1',_'M4') + 22*X_('P1',_'M5') + 16*X_('P1',_'M6') + 17*X_('P1',_'M7') + 15*X_('P1',_'M8') + 16*X_('P1',_'M9') + 13*X_('P10',_'M1') + 16*X_('P10',_'M10') + 14*X_('P10',_'M2') + 12*X_('P10',_'M3') + 16*X_('P10',_'M4') + 18*X_('P10',_'M5') + 17*X_('P10',_'M6') + 14*X_('P10',_'M7') + 14*X_('P10',_'M8') + 18*X_('P10',_'M9') + 14*X_('P11',_'M1') + 10*X_('P11',_'M10') + 9*X_('P11',_'M2') + 13*X_('P11',_'M3') + 13*X_('P11',_'M4') + 10*X_('P11',_'M5') + 12*X_('P11',_'M6') + 14*X_('P11',_'M7') + 12*X_('P11',_'M8') + 7*X_('P11',_'M9') + 29*X_('P12',_'M1') + 26*X_('P12',_'M10') + 30*X_('P12',_'M2') + 32*X_('P12',_'M3') + 23*X_('P12',_'M4') + 28*X_('P12',_'M5') + 28*X_('P12',_'M6') + 27*X_('P12',_'M7') + 26*X_('P12',_'M8') + 26*X_('P12',_'M9') + 34*X_('P13',_'M1') + 32*X_('P13',_'M10') + 32*X_('P13',_'M2') + 31*X_('P13',_'M3') + 35*X_('P13',_'M4') + 33*X_('P13',_'M5') + 27*X_('P

In [19]:
#prob.writeLP("blenderProblem.lp", writeSOS=1, mip=1)
prob.solve()
print("Status:", LpStatus[prob.status])
print ("Objective = ", value(prob.objective))
varsDict = {}
for v in prob.variables():
    varsDict[v.name] = v.varValue
    if "X" in v.name:
        print(v.name, "=", v.varValue)

Status: Optimal
Objective =  16990.0
X_('P1',_'M1') = 0.0
X_('P1',_'M10') = 0.0
X_('P1',_'M2') = 64.5
X_('P1',_'M3') = 0.0
X_('P1',_'M4') = 0.0
X_('P1',_'M5') = 0.0
X_('P1',_'M6') = 0.0
X_('P1',_'M7') = 0.0
X_('P1',_'M8') = 15.5
X_('P1',_'M9') = 0.0
X_('P10',_'M1') = 0.0
X_('P10',_'M10') = 0.0
X_('P10',_'M2') = 0.0
X_('P10',_'M3') = 2.0
X_('P10',_'M4') = 0.0
X_('P10',_'M5') = 0.0
X_('P10',_'M6') = 0.0
X_('P10',_'M7') = 0.0
X_('P10',_'M8') = 0.0
X_('P10',_'M9') = 0.0
X_('P11',_'M1') = 0.0
X_('P11',_'M10') = 0.0
X_('P11',_'M2') = 52.5
X_('P11',_'M3') = 0.0
X_('P11',_'M4') = 0.0
X_('P11',_'M5') = 0.0
X_('P11',_'M6') = 0.0
X_('P11',_'M7') = 0.0
X_('P11',_'M8') = 0.0
X_('P11',_'M9') = 3.5
X_('P12',_'M1') = 0.0
X_('P12',_'M10') = 0.0
X_('P12',_'M2') = 0.0
X_('P12',_'M3') = 0.0
X_('P12',_'M4') = 37.5
X_('P12',_'M5') = 0.0
X_('P12',_'M6') = 0.0
X_('P12',_'M7') = 7.5
X_('P12',_'M8') = 21.5
X_('P12',_'M9') = 23.5
X_('P13',_'M1') = 0.0
X_('P13',_'M10') = 0.0
X_('P13',_'M2') = 0.0
X_('P13',_'M3') 

In [20]:
for name, c in list(prob.constraints.items()):
     if "capacity" in name or "demand" in name:
        print(name, ":", c.pi, "\t\t", c.slack)

capacity_P1_ : -14.0 		 -0.0
capacity_P2_ : -21.0 		 -0.0
capacity_P3_ : 0.0 		 20.0
capacity_P4_ : 0.0 		 6.0
capacity_P5_ : -10.0 		 -0.0
capacity_P6_ : -18.0 		 -0.0
capacity_P7_ : -23.0 		 -0.0
capacity_P8_ : -9.0 		 -0.0
capacity_P9_ : 0.0 		 53.0
capacity_P10_ : -18.0 		 -0.0
capacity_P11_ : -22.0 		 -0.0
capacity_P12_ : -3.0 		 -0.0
capacity_P13_ : -1.0 		 -0.0
capacity_P14_ : -8.0 		 -0.0
capacity_P15_ : 0.0 		 -0.0
capacity_P16_ : -14.0 		 -0.0
capacity_P17_ : -6.0 		 -0.0
capacity_P18_ : -6.0 		 -0.0
capacity_P19_ : -7.0 		 -0.0
capacity_P20_ : -11.0 		 -0.0
demand_M1_ : 29.0 		 -0.0
demand_M2_ : 31.0 		 -0.0
demand_M3_ : 30.0 		 -0.0
demand_M4_ : 28.0 		 -0.0
demand_M5_ : 29.0 		 -0.0
demand_M6_ : 27.0 		 -0.0
demand_M7_ : 30.0 		 -0.0
demand_M8_ : 29.0 		 -0.0
demand_M9_ : 29.0 		 -0.0
demand_M10_ : 27.0 		 -0.0


In [21]:
#obj = 16847 (old) ==> new : Objective =  16990.0
#demand_M1_ : 29.0 		 -0.0
#demand_M2_ : 31.0 		 -0.0
#demand_M3_ : 30.0 		 -0.0
#demand_M4_ : 26.0 		 -0.0
#demand_M5_ : 29.0 		 -0.0
#demand_M6_ : 29.0 		 -0.0
#demand_M7_ : 29.0 		 -0.0
#demand_M8_ : 29.0 		 -0.0
#demand_M9_ : 29.0 		 -0.0
#demand_M10_ : 29.0 

#Dual Problem

In [92]:
B=[markets[j]['Demand'] for j in markets]+[plants[i]['Capacity'] for i in plants]
print(B)


[38, 129, 104, 75, 126, 90, 105, 91, 47, 61, 80, 9, 22, 69, 5, 81, 37, 18, 53, 2, 56, 90, 67, 45, 56, 49, 1, 96, 83, 26]


In [93]:
import numpy as np

A=np.zeros((30,230))
k=0
for i in range(10) :
        for j in range(20):
            A[i,j*10+k]=1.0
        k+=1
        
for i in range(10) :
    A[i,i+200]=-1.

for i in range(20) :
        for j in range(10):
            A[i+10,i*10+j]=1.0
        
for i in range(20) :
    A[i+10,i+210]=1.0
print(A)
tA=A.transpose()

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [126]:
C=[freightCost[i][j] + plants[i]['Cost'] for i in plants for j in markets ]+[0]*30
print(C)

[19, 17, 18, 19, 22, 16, 17, 15, 16, 22, 17, 17, 9, 18, 10, 12, 13, 15, 10, 11, 30, 34, 36, 30, 29, 37, 33, 34, 31, 29, 31, 34, 36, 36, 29, 31, 32, 36, 33, 34, 27, 21, 25, 22, 21, 22, 22, 29, 26, 21, 15, 17, 17, 17, 12, 9, 13, 12, 11, 9, 6, 12, 14, 15, 11, 14, 12, 6, 14, 10, 26, 23, 24, 26, 20, 21, 27, 26, 28, 24, 35, 33, 31, 30, 35, 33, 35, 30, 36, 33, 13, 14, 12, 16, 18, 17, 14, 14, 18, 16, 14, 9, 13, 13, 10, 12, 14, 12, 7, 10, 29, 30, 32, 23, 28, 28, 27, 26, 26, 26, 34, 32, 31, 35, 33, 27, 27, 30, 28, 32, 27, 27, 23, 20, 28, 22, 22, 25, 23, 24, 29, 35, 33, 32, 29, 32, 33, 32, 29, 33, 19, 17, 21, 17, 17, 13, 21, 17, 19, 13, 28, 25, 26, 24, 28, 29, 31, 23, 24, 26, 23, 27, 22, 23, 24, 21, 24, 23, 24, 26, 24, 24, 23, 22, 23, 28, 28, 22, 29, 29, 21, 25, 24, 18, 19, 22, 19, 25, 18, 21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [127]:
prob2 = LpProblem("Transportation_problem",LpMaximize)

In [128]:
Xvar2=LpVariable.dict("dual", (i for i in range(30)), lowBound=None, cat='Continuous')
print(Xvar2[1])

dual_1


In [129]:
prob2+= lpSum(Xvar2[i]*B[i] for i in Xvar2.keys())
for i in range(len(tA)) :
    K=[]
    for j in range(30):
        K+=Xvar2[j]*tA[i][j]
        print(j)
    prob2+= lpSum(K)<=C[i],"constraint [%s]]"%(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [130]:
print(prob2)

Transportation_problem:
MAXIMIZE
38*dual_0 + 129*dual_1 + 80*dual_10 + 9*dual_11 + 22*dual_12 + 69*dual_13 + 5*dual_14 + 81*dual_15 + 37*dual_16 + 18*dual_17 + 53*dual_18 + 2*dual_19 + 104*dual_2 + 56*dual_20 + 90*dual_21 + 67*dual_22 + 45*dual_23 + 56*dual_24 + 49*dual_25 + 1*dual_26 + 96*dual_27 + 83*dual_28 + 26*dual_29 + 75*dual_3 + 126*dual_4 + 90*dual_5 + 105*dual_6 + 91*dual_7 + 47*dual_8 + 61*dual_9 + 0
SUBJECT TO
constraint__0__: dual_0 + dual_10 <= 19

constraint__1__: dual_1 + dual_10 <= 17

constraint__2__: dual_10 + dual_2 <= 18

constraint__3__: dual_10 + dual_3 <= 19

constraint__4__: dual_10 + dual_4 <= 22

constraint__5__: dual_10 + dual_5 <= 16

constraint__6__: dual_10 + dual_6 <= 17

constraint__7__: dual_10 + dual_7 <= 15

constraint__8__: dual_10 + dual_8 <= 16

constraint__9__: dual_10 + dual_9 <= 22

constraint__10__: dual_0 + dual_11 <= 17

constraint__11__: dual_1 + dual_11 <= 17

constraint__12__: dual_11 + dual_2 <= 9

constraint__13__: dual_11 + dual_3 <= 1

In [131]:
#prob.writeLP("blenderProblem.lp", writeSOS=1, mip=1)
prob2.solve()
print("Status:", LpStatus[prob2.status])
print ("Objective = ", value(prob2.objective))
varsDict = {}

for v in prob2.variables():
    varsDict[v.name] = v.varValue
    if "dual" in v.name:
        print(v.name, "=", v.varValue)

Status: Optimal
Objective =  16846.999999999945
dual_0 = 29.0
dual_1 = 31.0
dual_10 = -14.0
dual_11 = -21.0
dual_12 = 0.0
dual_13 = 0.0
dual_14 = -10.0
dual_15 = -20.0
dual_16 = -23.0
dual_17 = -9.0
dual_18 = 0.0
dual_19 = -18.0
dual_2 = 30.0
dual_20 = -22.0
dual_21 = -3.0
dual_22 = -2.0
dual_23 = -7.0
dual_24 = -9.9831254e-13
dual_25 = -16.0
dual_26 = -6.0
dual_27 = -8.0
dual_28 = -7.0
dual_29 = -11.0
dual_3 = 26.0
dual_4 = 29.0
dual_5 = 29.0
dual_6 = 29.0
dual_7 = 29.0
dual_8 = 29.0
dual_9 = 29.0
